socket io
VerifiedInc/one-click-demo-web pull request #2
Opened 2024-02-19 20:57 UTC by iagormoraes

- chore: add socket.io and redis package
- chore: update env
- feat: listen and emit to room the success 1-click

[Ticket]()

## Summary

## Changes

## Testing

## Checklist

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas _to a borderline excessive amount_
- [ ] I have made any relevant corresponding changes to the documentation including the project readme.
- [ ] I have run and tested the changes locally
- [ ] If it is a core feature, I have added an appropriate amount of unit tests.
- [ ] Any dependent changes have been merged and published in upstream projects

2024-02-20 17:36 UTC, rsmets requested changes
We want to keep this project simple so anyone can run into locally easily. Having redis as a dependency greatly "complicates" things (even though it really doesn't). Just some words on wether it is really needed or not would be helpful.

2024-02-20 17:36 UTC, rsmets commented on .env.example
> +REDIS_URL=redis://localhost:6379
What happens if the REDIS_URL env is not provided? Will the project still work? I think so but mind adding a note in the README about this or at least here.

2024-02-20 17:44 UTC, iagormoraes commented on .env.example
> +REDIS_URL=redis://localhost:6379
It is required, but I will make the changes accordingly so that it can be optional.

2024-02-21 01:36 UTC, rsmets approved these changes

2024-02-21 01:40 UTC, merged